import fs from "node:fs/promises";
import { expect, test, type Page } from "@playwright/test";
import { loginAsAdmin } from "./helpers/admin-auth";
import { createNewsUploadFixtures } from "./helpers/news-upload-fixture";
import { startNetworkAudit } from "./helpers/network-audit";
import { adminApiToken } from "./helpers/admin-api-token";

const backend = () => process.env.KCIASSO_BACKEND_URL ?? "http://127.0.0.1:4479";
const runId = () => process.env.M8_RUN_ID ?? "local";
const transitionTitle = () => `[M8 ${runId()}] I7A5A transition`;

async function authToken(page: Page) { return adminApiToken(page); }
let seedCounter = 0;
async function uploadSeed(page: Page, file: string) { const token = await authToken(page); const source = await fs.readFile(file); const buffer = Buffer.concat([source, Buffer.from(`m8-${runId()}-${seedCounter++}`)]); const response = await page.request.post(`${backend()}/api/admin/news/media`, { headers: { authorization: `Bearer ${token}` }, multipart: { file: { name: `m8-${runId()}-seed.jpg`, mimeType: "image/jpeg", buffer } } }); return await response.json() as { key: string; url: string }; }
async function createNews(page: Page, coverImageUrl?: string | null) { const token = await authToken(page); const slug = `m8-${runId().toLowerCase()}-i7a5a-${Date.now()}-${Math.random().toString(16).slice(2)}`; const response = await page.request.post(`${backend()}/api/admin/news`, { headers: { authorization: `Bearer ${token}` }, data: { title: transitionTitle(), slug, excerpt: "transition", content: "transition", ...(coverImageUrl !== undefined ? { coverImageUrl } : {}) } }); if (!response.ok()) throw new Error(`seed news failed ${response.status()}`); return await response.json() as { id: number; slug: string; coverImageUrl?: string | null }; }
async function openEdit(page: Page, id: number) { await page.goto(`/admin/news/${id}/edit`); await expect(page.locator('input[name="title"]')).toHaveValue(transitionTitle()); }
async function patchAndRedirect(page: Page) { const patch = page.waitForResponse(response => response.url().match(/\/api\/admin\/news\/\d+$/) !== null && response.request().method() === "PATCH"); await page.locator('button[type="submit"]').click(); const response = await patch; expect(response.status()).toBe(200); await expect(page).toHaveURL(/\/admin\/news$/); }

test.describe("admin news cover transitions", () => {
  test("owned unchanged", async ({ page }) => { const audit = startNetworkAudit(page); const files = await createNewsUploadFixtures(); const seed = await uploadSeed(page, files.medium); const news = await createNews(page, seed.url); await loginAsAdmin(page); await openEdit(page, news.id); await expect(page.getByRole("img", { name: /Предпросмотр изображения новости/ })).toBeVisible(); await expect(page.getByLabel(/Ссылка на изображение/)).not.toBeVisible(); await patchAndRedirect(page); await openEdit(page, news.id); await expect(page.getByRole("img", { name: /Предпросмотр изображения новости/ })).toBeVisible(); audit.assertClean(); });
  test("owned to new owned", async ({ page }) => { const audit = startNetworkAudit(page); const files = await createNewsUploadFixtures(); const old = await uploadSeed(page, files.medium); const news = await createNews(page, old.url); await loginAsAdmin(page); await openEdit(page, news.id); const patch = page.waitForRequest(request => request.url().match(/\/api\/admin\/news\/\d+$/) !== null && request.method() === "PATCH"); await page.locator('input[type="file"]').setInputFiles(files.medium); await page.locator('button[type="submit"]').click(); const body = patch.then(request => request.postDataJSON()); await expect(page).toHaveURL(/\/admin\/news$/); expect((await body).cover.kind).toBe("set"); expect((await page.request.get(old.url)).status()).toBe(404); audit.assertClean(); });
  test("owned to external is blocked until server import", async ({ page }) => { const audit = startNetworkAudit(page); const files = await createNewsUploadFixtures(); const old = await uploadSeed(page, files.medium); const news = await createNews(page, old.url); await loginAsAdmin(page); await openEdit(page, news.id); await page.getByRole("button", { name: /Указать ссылку/ }).click(); await page.locator('input[inputmode="url"]').fill("https://example.test/new-cover.jpg"); const patches: string[] = []; page.on("request", request => { if (request.method() === "PATCH") patches.push(request.url()); }); await page.locator('button[type="submit"]').click(); await expect(page.locator('p[role="alert"]')).toContainText("сервер"); expect(patches).toHaveLength(0); expect((await page.request.get(old.url)).status()).toBe(200); audit.assertClean(); });
  test("owned to remove", async ({ page }) => { const audit = startNetworkAudit(page); const files = await createNewsUploadFixtures(); const old = await uploadSeed(page, files.medium); const news = await createNews(page, old.url); await loginAsAdmin(page); await openEdit(page, news.id); await page.getByRole("button", { name: "Удалить изображение" }).click(); const patch = page.waitForRequest(request => request.method() === "PATCH" && request.url().includes(`/api/admin/news/${news.id}`)); await page.locator('button[type="submit"]').click(); expect((await patch).postDataJSON().cover).toEqual({ kind: "remove" }); await expect(page).toHaveURL(/\/admin\/news$/); expect((await page.request.get(old.url)).status()).toBe(404); audit.assertClean(); });
  test("external unchanged", async ({ page }) => { const audit = startNetworkAudit(page); const news = await createNews(page, "https://example.test/original.jpg"); await loginAsAdmin(page); await openEdit(page, news.id); await expect(page.locator('input[inputmode="url"]')).toHaveValue("https://example.test/original.jpg"); const patch = page.waitForRequest(request => request.method() === "PATCH" && request.url().includes(`/api/admin/news/${news.id}`)); await page.locator('button[type="submit"]').click(); expect((await patch).postDataJSON().cover).toEqual({ kind: "unchanged" }); await expect(page).toHaveURL(/\/admin\/news$/); audit.assertClean(); });
  test("external to owned", async ({ page }) => { const audit = startNetworkAudit(page); const news = await createNews(page, "https://example.test/original.jpg"); const files = await createNewsUploadFixtures(); await loginAsAdmin(page); await openEdit(page, news.id); await page.getByRole("button", { name: /Загрузить файл/ }).click(); const patch = page.waitForRequest(request => request.method() === "PATCH" && request.url().includes(`/api/admin/news/${news.id}`)); await page.locator('input[type="file"]').setInputFiles(files.medium); await page.locator('button[type="submit"]').click(); expect((await patch).postDataJSON().cover.source).toBe("owned"); await expect(page).toHaveURL(/\/admin\/news$/); audit.assertClean(); });
  test("external replacement is blocked until server import", async ({ page }) => { const audit = startNetworkAudit(page); const news = await createNews(page, "https://example.test/original.jpg"); await loginAsAdmin(page); await openEdit(page, news.id); await page.locator('input[inputmode="url"]').fill("https://example.test/replacement.jpg"); const patches: string[] = []; page.on("request", request => { if (request.method() === "PATCH") patches.push(request.url()); }); await page.locator('button[type="submit"]').click(); await expect(page.locator('p[role="alert"]')).toContainText("сервер"); expect(patches).toHaveLength(0); audit.assertClean(); });
  test("external to remove", async ({ page }) => { const audit = startNetworkAudit(page); const news = await createNews(page, "https://example.test/original.jpg"); await loginAsAdmin(page); await openEdit(page, news.id); await page.getByRole("button", { name: "Удалить изображение" }).click(); const patch = page.waitForRequest(request => request.method() === "PATCH" && request.url().includes(`/api/admin/news/${news.id}`)); await page.locator('button[type="submit"]').click(); expect((await patch).postDataJSON().cover).toEqual({ kind: "remove" }); await expect(page).toHaveURL(/\/admin\/news$/); audit.assertClean(); });
  test("none to owned", async ({ page }) => { const audit = startNetworkAudit(page); const news = await createNews(page); const files = await createNewsUploadFixtures(); await loginAsAdmin(page); await openEdit(page, news.id); const patch = page.waitForRequest(request => request.method() === "PATCH" && request.url().includes(`/api/admin/news/${news.id}`)); await page.locator('input[type="file"]').setInputFiles(files.medium); await page.locator('button[type="submit"]').click(); expect((await patch).postDataJSON().cover.source).toBe("owned"); await expect(page).toHaveURL(/\/admin\/news$/); audit.assertClean(); });
  test("none to external is blocked until server import", async ({ page }) => { const audit = startNetworkAudit(page); const news = await createNews(page); await loginAsAdmin(page); await openEdit(page, news.id); await page.getByRole("button", { name: /Указать ссылку/ }).click(); await page.locator('input[inputmode="url"]').fill("https://example.test/new.jpg"); const patches: string[] = []; page.on("request", request => { if (request.method() === "PATCH") patches.push(request.url()); }); await page.locator('button[type="submit"]').click(); await expect(page.locator('p[role="alert"]')).toContainText("сервер"); expect(patches).toHaveLength(0); audit.assertClean(); });
  test("invalid external URL stays inline and sends no PATCH", async ({ page }) => { const audit = startNetworkAudit(page); const news = await createNews(page, "https://example.test/original.jpg"); await loginAsAdmin(page); await openEdit(page, news.id); const input = page.locator('input[inputmode="url"]'); await input.fill("ftp://bad.example/image.jpg"); const requests: string[] = []; page.on("request", request => { if (request.method() === "PATCH") requests.push(request.url()); }); await page.locator('button[type="submit"]').click(); await expect(page.locator('p[role="alert"]')).toBeVisible(); expect(requests).toHaveLength(0); await expect(input).toHaveValue("ftp://bad.example/image.jpg"); audit.assertClean(); });
});
